"""The discovery contracts: --catalog json (vs. the live parser) and rules --json."""
from __future__ import annotations

import argparse
import json

import pytest

import contract_lint_cli as cl
from conftest import assert_valid


def test_catalog_shape() -> None:
    cat = cl.build_catalog()
    for key in ("name", "bin", "version", "description", "commands", "exitCodes"):
        assert key in cat
    assert cat["name"] == cat["bin"] == "contract-lint"
    assert cat["version"] == cl.__version__
    assert set(cat["exitCodes"]) == {"0", "1", "2"}
    # standalone-first: the description leads with what it does, not "the X layer of the suite".
    assert cat["description"].lower().startswith("lint a contract")


def test_catalog_lists_every_command_and_flag() -> None:
    """The catalog is generated by walking the parser, so it must match it exactly."""
    parser = cl.build_parser()
    sub = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    cat = {c["name"]: c for c in cl.build_catalog()["commands"]}
    assert set(cat) == set(sub.choices)
    for name, subparser in sub.choices.items():
        live_flags = {
            a.option_strings[-1]
            for a in subparser._actions
            if a.option_strings and a.help != argparse.SUPPRESS
        }
        cat_flags = {f["name"] for f in cat[name]["flags"]}
        assert cat_flags == live_flags, f"catalog drift for {name}: {cat_flags ^ live_flags}"
        for f in cat[name]["flags"]:
            assert set(f) == {"name", "aliases", "help", "required", "default", "choices"}


def test_catalog_command_summaries_present() -> None:
    for c in cl.build_catalog()["commands"]:
        assert c["summary"], f"command {c['name']} missing a summary"


def test_rules_json_matches_registry(capsys: pytest.CaptureFixture[str], rules_schema: dict) -> None:
    code = cl.main(["rules", "--json"])
    assert code == 0
    payload = json.loads(capsys.readouterr().out)
    assert_valid(payload, rules_schema)
    assert payload["tool"] == "contract-lint"
    by_id = {r["id"]: r for r in payload["rules"]}
    assert set(by_id) == {r.id for r in cl.RULES}
    for r in cl.RULES:
        assert by_id[r.id]["severity"] == r.severity
        assert by_id[r.id]["default_enabled"] == r.default_enabled
        assert by_id[r.id]["description"] == r.description


def test_rules_human_table(capsys: pytest.CaptureFixture[str]) -> None:
    code = cl.main(["rules"])
    assert code == 0
    out = capsys.readouterr().out
    for r in cl.RULES:
        assert r.id in out


def test_completion_scripts() -> None:
    for shell in ("bash", "zsh"):
        code = cl.main(["completion", shell])
        assert code == 0


def test_complete_helper_never_errors() -> None:
    assert cl.cmd_complete([]) == 0
    assert cl.cmd_complete(["lint", "--fail-on", ""]) == 0
    assert cl.cmd_complete(["completion", "ba"]) == 0
